baseURL = "https://join.lemmy.world/"
languageCode = "en-US"
title = "Join Lemmy.World"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-9555PS4FGD"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "/images/favicon.png"
  author = "Lemmy World"
  description = "Join Lemmy.World"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["/main.css"]
  custom_js  = []

[params.social]
  Mastodon       = "https://mastodon.world/@LemmyWorld"
  Github        = "LemmyWorld"
  Discord = "https://discord.gg/lemmyworld"
  Matrix = "https://matrix.to/#/#lemmyworld:h-y-p-e-r.space"
  # Email         = "info@lemmy.world"
  LinkedIn      = "https://www.linkedin.com/company/lemmyworld/"
  Minecraft = "http://map.minecraft.lemmy.world/"
  GooglePlay = "https://play.google.com/store/apps/details?id=io.syncapps.lemmy_sync"
  Apple = "https://apps.apple.com/us/app/memmy-for-lemmy/id6450204299"
Patreon ="https://patreon.com/mastodonworld"
Donate = 'https://opencollective.com/mastodonworld'

## Main Menu

[[menu.main]]
  name = "💬 Discord"
  weight = 1
  identifier = "legal"
  url = "https://discord.gg/lemmyworld"

[[menu.main]]
  name = "📔 Blog"
  weight = 2
  identifier = "blog"
  url = "https://blog.lemmy.world"

[[menu.main]]
  name = "🧑 Join our Team"
  weight = 99
  identifier = "team"
  url = "https://team.lemmy.world"


