baseURL = "https://join.lemmy.world/"
languageCode = "en-US"
title = "Join Lemmy.World"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
#googleAnalytics = "G-9555PS4FGD"
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  author = "Lemmy World"
  description = "Come for the memes, stay for the community"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["/main.css"]
  custom_js  = []

[params.social]
  # Mastodon       = "https://mastodon.world/@LemmyWorld"
  Github        = "LemmyWorld"
  # Discord = "https://discord.gg/lemmyworld"
  # Matrix = "https://matrix.to/#/#general:lemmy.world"
  # Email         = "info@lemmy.world"
  LinkedIn      = "https://www.linkedin.com/company/lemmyworld/"
  Minecraft = "http://map.minecraft.lemmy.world/"
  # GooglePlay = "https://play.google.com/store/apps/details?id=io.syncapps.lemmy_sync"
  # Apple = "https://apps.apple.com/us/app/memmy-for-lemmy/id6450204299"
Patreon ="https://patreon.com/mastodonworld"
Donate = 'https://opencollective.com/mastodonworld'

## Main Menu

[[menu.main]]
  name = "📔 Blog"
  weight = 1
  identifier = "blog"
  url = "https://blog.lemmy.world"

[[menu.main]]
  name = "🖥 Page Status"
  weight = 2
  identifier = "uptime"
  url = "https://dash.lemmy.world"

[[menu.main]]
  name = "🧑 Join our Team"
  weight = 98
  identifier = "team"
  url = "https://team.lemmy.world"
